### ISSUE TITLE
pytest-warning due to a deprecated argument

### ISSUE THREAD

**Issue by Antoine25** [EverythingMe/pytest-blocker#2]
Hello :)

I'am using your plugin (_pytest-blocker-0.2_) with a pytest version 2.8.3 and i have this pytest-warning when i run my tests : 

**WI1 .../pytest_blocker/**init**.py:15 'pytest_runtest_makereport' hook uses deprecated **multicall** argument**

Is there any plan to fix this ?

Thank you very much !!

**Comment by maticrivo** [comment]
Hey, thanks, i will try getting to this next week.

**Comment by Antoine25** [comment]
Ok thank you ! :+1:

**Comment by ranbena** [comment]
Landed fix
